// Assemble docs/validation-report.md from the JSON outputs of the corpus tools.
//
//   node scripts/corpus/write-report.mjs
//
// Every number in the report comes from a committed JSON file under data/, so
// the report can be regenerated and checked.
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const read = (path) => (existsSync(path) ? JSON.parse(readFileSync(path, "utf8")) : null);
const GRADES = ["brilliant", "great", "best", "excellent", "good", "book", "inaccuracy", "mistake", "miss", "blunder"];
const LABEL = { brilliant: "Brilliant", great: "Great", best: "Best", excellent: "Excellent", good: "Good", book: "Book", inaccuracy: "Inaccuracy", mistake: "Mistake", miss: "Miss", blunder: "Blunder" };
const lines = [];
const out = (text = "") => lines.push(text);
const table = (header, rows) => {
  out(`| ${header.join(" | ")} |`);
  out(`| ${header.map(() => "---").join(" | ")} |`);
  for (const row of rows) out(`| ${row.join(" | ")} |`);
  out();
};

out("# KnightScope validation report");
out();
out("Generated by `node scripts/corpus/write-report.mjs` from the JSON files under `data/`. Regenerate after any classifier or rating-model change.");
out();

// 1. Golden games before / after.
const goldenBefore = read("data/golden/report-before.json");
const goldenAfter = read("data/golden/report-after.json");
if (goldenBefore && goldenAfter) {
  out("## 1. Great / Brilliant on the two famous games (before → after)");
  out();
  out("Same cached Stockfish searches (Balanced, 150k nodes) for both versions; only the classifier differs.");
  out();
  for (let index = 0; index < goldenAfter.length; index += 1) {
    const before = goldenBefore[index];
    const after = goldenAfter[index];
    out(`### ${after.title}`);
    out();
    const rows = [];
    after.moves.forEach((move, ply) => {
      const old = before.moves[ply];
      if (!["great", "brilliant"].includes(old.grade) && !["great", "brilliant"].includes(move.grade)) return;
      const why = move.grade === "brilliant"
        ? "Brilliant kept"
        : move.grade === "great"
          ? `${old.grade === "brilliant" ? `not Brilliant (${move.brilliant?.decision.replace("rejected: ", "")}); ` : ""}${move.great?.greatReason ?? ""}`
          : old.grade === "brilliant" && move.brilliant
            ? move.brilliant.decision
            : move.great?.decision ?? "";
      rows.push([move.move, LABEL[old.grade], LABEL[move.grade], why.replace(/\|/g, "/")]);
    });
    table(["Move", "Before (ks-review-2.0)", "After", "Why"], rows);
  }
}

// 2. Brilliant adversarial suite.
const suite = read("data/brilliant-suite/report.json");
if (suite) {
  out("## 2. Brilliant adversarial suite");
  out();
  const byCategory = {};
  for (const result of suite.results) (byCategory[result.category] ??= []).push(result);
  const rows = Object.entries(byCategory).map(([category, results]) => [
    category,
    results[0].mustNotBeBrilliant ? "must not be Brilliant" : "sound sacrifice (Brilliant allowed)",
    String(results.length),
    String(results.filter((result) => result.grade === "brilliant").length),
    results.map((result) => `${result.move} → ${LABEL[result.grade]}${result.brilliantDiagnostics ? ` (${result.brilliantDiagnostics.decision})` : ""}`).join("; "),
  ]);
  table(["Category", "Expectation", "Cases", "Brilliant", "Results"], rows);
  const falsePositives = suite.results.filter((result) => result.mustNotBeBrilliant && result.grade === "brilliant").length;
  out(`False positives: **${falsePositives}** of ${suite.results.filter((result) => result.mustNotBeBrilliant).length} must-not cases. Engine: ${suite.engine}, preset ${suite.preset}.`);
  out();
}

// 3. Classification distribution.
const writeDistribution = (title, report, before) => {
  if (!report) return;
  out(`### ${title}`);
  out();
  out(`${report.games} games, ${report.overall.moves} moves. Rates per 1000 moves.`);
  out();
  const header = ["Band", "Moves", ...GRADES.map((grade) => LABEL[grade])];
  const rows = [];
  if (before) rows.push(["**all, before**", String(before.overall.moves), ...GRADES.map((grade) => String(before.overall.per1000[grade] ?? 0))]);
  rows.push([before ? "**all, after**" : "**all**", String(report.overall.moves), ...GRADES.map((grade) => String(report.overall.per1000[grade]))]);
  for (const [band, value] of Object.entries(report.byBand)) rows.push([band, String(value.moves), ...GRADES.map((grade) => String(value.per1000[grade]))]);
  table(header, rows);
  out(`Great per side per game: mean ${report.greatPerSideGame.mean}, max ${report.greatPerSideGame.max}${before ? ` (before: mean ${before.greatPerSideGame.mean}, max ${before.greatPerSideGame.max})` : ""}.`);
  out();
  out("Pathology checks:");
  out();
  const p = report.pathologies;
  out(`- sides with more than 3 Great moves in one game: ${p.sidesWithMoreThan3Great.length}${p.sidesWithMoreThan3Great.length ? ` (${p.sidesWithMoreThan3Great.join(", ")})` : ""}`);
  out(`- Great recaptures: ${p.greatRecaptures.length}; Great although the best alternative still kept a better/winning position with the same engine verdict: ${p.greatWhileDecided.length}`);
  out(`- Brilliant without a detected sacrifice: ${p.brilliantsWithoutSacrifice.length}; Brilliant where a quiet move already won: ${p.brilliantsWhereAlternativeAlreadyWon.length}; Brilliant from a worse position (< 40%): ${p.brilliantsFromLosingPositions.length}; consecutive Brilliants by one side: ${p.consecutiveBrilliantsSameSide.length}`);
  out(`- Miss share of tactical errors (Mistake + Miss + Blunder): ${p.missShareOfTacticalErrors}`);
  out(`- Book: moves losing more than 0.05 EP shown as Book: ${p.bookMovesLosingOver5Points}; last Book ply per game: median ${p.bookPliesMedian}, 95th percentile ${p.bookPliesP95}, max ${p.maxBookPly}; games that show Book again after a non-Book move: ${p.bookAfterNonBookMove} (a theory move graded on its merits because it lost ≥ 0.05, or a transposition back into theory)`);
  out();
  if (report.greatDecisions) {
    out("Great candidates (near-best and unique) and the rule that decided them:");
    out();
    table(["Decision", "Count"], Object.entries(report.greatDecisions).sort((a, b) => b[1] - a[1]).map(([key, value]) => [key, String(value)]));
  }
  if (report.brilliantDecisions) {
    out("Brilliant candidates (near-best moves that give up material):");
    out();
    table(["Decision", "Count"], Object.entries(report.brilliantDecisions).sort((a, b) => b[1] - a[1]).map(([key, value]) => [key, String(value)]));
  }
};
const validationAfter = read("data/validation-corpus/stats-after.json");
const validationBefore = read("data/validation-corpus/stats-before.json");
const ratingCorpusStats = read("data/rating-corpus/stats-after.json");
if (validationAfter || ratingCorpusStats) {
  out("## 3. Classification distribution");
  out();
  writeDistribution("Validation corpus (curated, Balanced preset)", validationAfter, validationBefore);
  if (validationAfter) {
    out("By corpus tag (per 1000 moves):");
    out();
    table(["Tag", "Moves", ...GRADES.map((grade) => LABEL[grade])], Object.entries(validationAfter.byTag).map(([tag, value]) => [tag, String(value.moves), ...GRADES.map((grade) => String(value.per1000[grade]))]));
  }
  writeDistribution("Rated-game corpus (Quick preset), by player rating", ratingCorpusStats, null);
}

// 4–7. Rating (the newest corpus that has a benchmark).
const CORPUS = existsSync("data/rating-corpus-v2/benchmark.json") ? "data/rating-corpus-v2" : "data/rating-corpus";
const summary = read(`${CORPUS}/dataset-summary.json`);
const manifest = read(`${CORPUS}/MANIFEST.json`) ?? read(`${CORPUS}/FILTERS.json`);
const bench = read(`${CORPUS}/benchmark.json`);
const coverageRows = (report) => [
  ["overall", "", String(report.coverage), String(report.meanWidth)],
  ...Object.entries(report.byPredictedBand).map(([key, v]) => [`predicted ${key}`, String(v.n), String(v.coverage), String(v.meanWidth)]),
  ...Object.entries(report.byTrueBand).map(([key, v]) => [`true ${key}`, String(v.n), String(v.coverage), String(v.meanWidth)]),
  ...Object.entries(report.byDecisions).map(([key, v]) => [`${key} decisions`, String(v.n), String(v.coverage), String(v.meanWidth)]),
  ...Object.entries(report.byGameLength).map(([key, v]) => [key, String(v.n), String(v.coverage), String(v.meanWidth)]),
];
if (summary && bench?.timeControls?.blitz?.cv) {
  out("## 4. Rating dataset");
  out();
  out(`Corpus \`${CORPUS}\`: ${summary.games} rated Lichess games → ${summary.samples} player-games from ${summary.players} players (analyzed at the ${summary.preset} preset, ${summary.engine}).`);
  out();
  if (manifest?.month) {
    out(`Source: ${manifest.source} (${manifest.license}), month ${manifest.month}, seed ${manifest.seed}; ${manifest.gamesRead.toLocaleString()} games streamed, ${manifest.eligible.toLocaleString()} eligible, ${manifest.selected} selected (${manifest.perStratum} per stratum, at most ${manifest.perPlayerCap} per player). ${manifest.selection}.`);
    out();
    table(["Filter", "Dropped"], Object.values(manifest.filters).map((filter) => [filter.description, String(filter.dropped)]));
  }
  table(["Time control", ...Object.keys(summary.byTimeControlAndBand.blitz)], ["blitz", "rapid"].map((tc) => [tc, ...Object.values(summary.byTimeControlAndBand[tc]).map(String)]));
  out("## 5. Split");
  out();
  out(`${summary.splitMethod[0].toUpperCase()}${summary.splitMethod.slice(1)}. Players appearing in more than one split: **${summary.leakingPlayers}**.`);
  out();
  if (summary.splitDetail) {
    table(["Split", "Player-games", "Players", "Connected groups", "Games", "Blitz", "Rapid"], Object.entries(summary.splitDetail).map(([split, v]) => [split, String(v.playerGames), String(v.players), String(v.connectedGroups), String(v.games), String(v.byTimeControl.blitz), String(v.byTimeControl.rapid)]));
  }
  out("Every choice (model family, hyperparameters, weighting, calibration layer, interval model) was made by 5-fold player-grouped cross-validation on train + validation. Test was scored once, after those choices were frozen.");
  out();
  out("## 6. Held-out accuracy, calibration and intervals");
  out();
  for (const [tc, report] of Object.entries(bench.timeControls)) {
    out(`### ${tc}: chosen model \`${report.chosen}\`${report.calibrationLayer?.used ? " + isotonic calibration" : ""}`);
    out();
    out("Cross-validated (train + validation, out-of-fold):");
    out();
    table(["Model", "Param", "MAE", "± SE", "Median AE", "RMSE", "R²"], Object.entries(report.cv).map(([name, m]) => [name, JSON.stringify(m.param ?? ""), String(m.mae), String(m.se ?? ""), String(m.medianAe ?? ""), String(m.rmse ?? ""), String(m.r2 ?? "")]));
    if (report.test) {
      out(`Test (n = ${report.test.shipped.n}):`);
      out();
      table(["Model", "MAE", "Median AE", "RMSE", "R²", "Bias"], Object.entries(report.test).map(([name, m]) => [name, String(m.mae), String(m.medianAe), String(m.rmse), String(m.r2), String(m.bias)]));
      const models = Object.keys(report.testByTrueBand);
      out("Test MAE (bias) by true rating band:");
      out();
      table(["Band", "n", ...models], Object.keys(report.testByTrueBand.shipped).map((band) => [band, String(report.testByTrueBand.shipped[band].n), ...models.map((model) => { const v = report.testByTrueBand[model][band]; return v ? `${v.mae} (${v.bias > 0 ? "+" : ""}${v.bias})` : ""; })]));
      if (report.testByDecisions) {
        out("Test MAE (bias) by meaningful-decision count:");
        out();
        const decModels = Object.keys(report.testByDecisions);
        const decKeys = Object.keys(report.testByDecisions.shipped ?? {});
        table(["Decisions", "n", ...decModels], decKeys.map((key) => [key, String(report.testByDecisions.shipped[key].n), ...decModels.map((model) => { const v = report.testByDecisions[model][key]; return v ? `${v.mae} (${v.bias > 0 ? "+" : ""}${v.bias})` : ""; })]));
      }
    }
    out("Why the extremes are biased (out-of-fold, chosen model): bias by true band × meaningful decisions. If more decisions shrink the bias, the cause is missing information in one game rather than model form.");
    out();
    table(["Band | decisions", "n", "Bias"], Object.entries(report.extremeBiasDiagnosis.oofBiasByBandAndDecisions).map(([key, v]) => [key, String(v.n), String(v.bias)]));
    out(`Attenuation: slope of the estimate on the true rating = ${report.extremeBiasDiagnosis.attenuationSlopePredictedOnActual} (1 would mean no shrinkage).`);
    out();
    out(`#### ${tc}: calibration of the point estimate (out-of-fold)`);
    out();
    const layer = report.calibrationLayer;
    out(`Mean actual rating by predicted range. Calibration error (weighted mean |gap|): ${layer.without.calibrationError} without, ${layer.withIsotonic.calibrationError} with the isotonic layer; OOF MAE ${layer.without.mae} → ${layer.withIsotonic.mae}. Layer used: **${layer.used ? "yes" : "no"}**. Slope of actual on predicted: ${layer.without.slopeActualOnPredicted}.`);
    out();
    table(["Predicted", "n", "Mean predicted", "Mean actual", "Gap"], layer.without.bins.map((b) => [b.predicted, String(b.n), String(b.meanPredicted), String(b.meanActual), String(b.gap)]));
    if (report.testIntervals) {
      out(`#### ${tc}: interval coverage (test, nominal ${bench.level * 100}%)`);
      out();
      for (const [name, value] of Object.entries(report.testIntervals)) {
        out(`**${name}**`);
        out();
        table(["Subgroup", "n", "Coverage", "Mean width"], coverageRows(value));
      }
    }
  }
}

// Outcome model.
const outcome = read(`${CORPUS}/outcome-model.json`) ?? read("data/rating-corpus/outcome-model.json");
if (outcome) {
  out("## 7. Rating-conditioned outcome model E[result | cp, rating, time control]");
  out();
  out(`Positions (side to move, own-engine cp, final score): train ${outcome.positions.train}, validation ${outcome.positions.validation}, test ${outcome.positions.test}. Chosen on validation: **${outcome.chosen}** (simplest model not significantly worse than the best, by a player-grouped bootstrap).`);
  out();
  table(["Model", "Val log loss", "Brier", "Calibration error", "Constraints"], Object.entries(outcome.models).map(([name, m]) => [name, String(m.validation.logLoss), String(m.validation.brier), String(m.validation.ece), m.constraints ? (m.constraints.monotoneAndNeutral ? `monotone, neutral; E(+3000 cp) ≥ ${m.constraints.minTailAt3000cp}` : "VIOLATED") : ""]));
  out(`Log-loss improvement over the fixed Lichess curve (validation, 95% CI): ${JSON.stringify(outcome.chosenVsBaselineCI)}.`);
  out();
  if (outcome.test) {
    out(`Test: chosen ${JSON.stringify(outcome.test.chosen)}, baseline ${JSON.stringify(outcome.test.baseline)}.`);
    out();
  }
  if (outcome.representativeCurves) {
    out("Expected score at representative evaluations (chosen model vs the fixed baseline curve):");
    out();
    const rcps = Object.keys(outcome.representativeCurves.baseline);
    table(["tc | band", ...rcps.map((cp) => (Number(cp) >= 0 ? `+${cp}` : cp))], Object.entries(outcome.representativeCurves).map(([key, v]) => [key, ...rcps.map((cp) => String(v[cp]))]));
  }
  out("Expected score at fixed cp by rating band (chosen model):");
  out();
  const cps = Object.keys(outcome.curves.baseline);
  table(["tc | band", ...cps.map((cp) => `+${cp}`)], Object.entries(outcome.curves).map(([key, v]) => [key, ...cps.map((cp) => String(v[cp]))]));
  out("Validation log loss by rating band, chosen vs baseline:");
  out();
  table(["Band", "n", "Chosen", "Baseline"], Object.entries(outcome.validationByBand.chosen).map(([band, v]) => [band, String(v.n), String(v.logLoss), String(outcome.validationByBand.baseline[band]?.logLoss)]));
}
const regrade = read(`${CORPUS}/regrade.json`);
if (regrade) {
  out("### Would the rating-conditioned curve change displayed grades? (test players)");
  out();
  out("Not enabled automatically; shown as evidence. \"true\" grades at the player's real rating (oracle); \"est\" grades at this session's single-game estimate (what the app could actually do, step 2 → step 3, no feedback).");
  out();
  const byBand = regrade.byBand ?? regrade.bands;
  out("By rating band:");
  out();
  table(["Band", "Moves", "Blunder base → true / est", "Mistake base → true / est", "Inaccuracy base → true / est", "Grades changed (true / est)"],
    Object.entries(byBand).map(([band, v]) => [band, String(v.moves),
      `${v.baseline.blunder} → ${v.ratedAtTrueRating.blunder} / ${v.ratedAtEstimate.blunder}`,
      `${v.baseline.mistake} → ${v.ratedAtTrueRating.mistake} / ${v.ratedAtEstimate.mistake}`,
      `${v.baseline.inaccuracy} → ${v.ratedAtTrueRating.inaccuracy} / ${v.ratedAtEstimate.inaccuracy}`,
      `${Math.round(v.changedShare.trueRating * 100)}% / ${Math.round(v.changedShare.estimate * 100)}%`]));
  if (regrade.byTimeControl) {
    out("By time control:");
    out();
    table(["Time control", "Moves", "Grades changed (true / est)"],
      Object.entries(regrade.byTimeControl).map(([tc, v]) => [tc, String(v.moves), `${Math.round(v.changedShare.trueRating * 100)}% / ${Math.round(v.changedShare.estimate * 100)}%`]));
  }
  if (regrade.byCurrentGrade) {
    out("By CURRENT (baseline) classification — how often does a move shown as each grade today change under the rating-conditioned curve:");
    out();
    table(["Current grade", "Moves", "Grades changed (true / est)"],
      Object.entries(regrade.byCurrentGrade).map(([grade, v]) => [LABEL[grade] ?? grade, String(v.moves), `${Math.round(v.changedShare.trueRating * 100)}% / ${Math.round(v.changedShare.estimate * 100)}%`]));
  }
}
const nativePositions = read("data/golden/native-parity-positions.json");
const nativeGames = read("data/golden/native-parity-games.json");
if (nativePositions || nativeGames) {
  out("### Native vs WASM engine equivalence");
  out();
  out("The native build (scripts/corpus/build-native-engine.sh) is the same vendored stockfish.js 19.0.0 source and Lite network the browser runs, compiled to a native binary purely for corpus-analysis speed. Used to generate rating/outcome-model training data only if equivalent to the browser build at the level the models consume.");
  out();
  if (nativePositions) {
    const p = nativePositions.summary;
    table(["Metric", "Value"], [
      ["Positions compared", String(p.positions)],
      ["Nodes / MultiPV", `${p.nodes} / ${p.multiPv}`],
      ["By phase", JSON.stringify(p.byPhase)],
      ["Best-move mismatches", `${p.bestMoveMismatchCount} (${p.bestMoveMismatchRate})`],
      ["Candidate-order mismatches (MultiPV)", `${p.candidateOrderMismatchCount} (${p.candidateOrderMismatchRate})`],
      ["Root cp diff (max / mean / nonzero)", `${p.cpDiff.max} / ${p.cpDiff.mean} / ${p.cpDiff.nonZeroCount}`],
      ["Baseline expected-score diff (max / mean / nonzero)", `${p.baselineExpectedScoreDiff.max} / ${p.baselineExpectedScoreDiff.mean} / ${p.baselineExpectedScoreDiff.nonZeroCount}`],
      ["Mate-field mismatches", String(p.mateFieldMismatches)],
    ]);
  }
  if (nativeGames) {
    const g = nativeGames.summary;
    table(["Metric", "Value"], [
      ["Full games compared (primary + candidate + verification passes)", String(g.gamesCompared)],
      ["Exact per-move match", `${g.exactMatches}/${g.gamesCompared} (${g.exactMatchRate})`],
      ["Feature vectors compared (both sides)", String(g.featureVectorsCompared)],
      ["Max feature-vector diff", `${g.maxFeatureDiff}${g.maxFeatureDiffName ? ` (${g.maxFeatureDiffName})` : ""}`],
      ["Max root cp diff", String(g.maxRootCpDiff)],
      ["Native speedup", `${g.speedup}x (wasm ${g.wasmSecondsTotal}s, native ${g.nativeSecondsTotal}s)`],
    ]);
  }
  out();
}
const scale = read("data/golden/engine-scale.json");
if (scale) {
  out("### Lite vs Full centipawn scale");
  out();
  out(`${scale.summary.compared} positions at ${scale.summary.nodes} nodes: slope of Lite cp on Full cp ${scale.summary.slopeLiteOnFull}, median ratio ${scale.summary.medianRatioLiteOverFull}, mean |cp| Lite ${scale.summary.meanAbsCp.lite} vs Full ${scale.summary.meanAbsCp.full}, sign agreement ${scale.summary.signAgreement}.`);
  out();
}

// Brilliant validation.
const brilliantVal = read("data/brilliant-suite/validation-report.json");
if (brilliantVal) {
  out("## 8. Brilliant validation");
  out();
  out("Reported separately per the validation protocol: the automatically constructed corpus (labels from Lichess's puzzle generator and Lichess's own game analysis / the actual game, never from KnightScope's rule) and a smaller, hand-audited gold subset (individually selected/constructed positions, including borderline sacrifices scored qualitatively rather than pass/fail). The Brilliant algorithm itself was not modified in response to this validation pass.");
  out();
  const writeMetrics = (title, r) => {
    out(`### ${title}`);
    out();
    out(`${r.positives} positives, ${r.negatives} negatives${r.ambiguousCases?.length ? `, ${r.ambiguousCases.length} ambiguous (unscored)` : ""}.`);
    out();
    table(["Metric", "Value", "95% CI (Wilson)"], [
      ["Precision", String(r.precision), JSON.stringify(r.precisionCI95)],
      ["Recall", String(r.recall), JSON.stringify(r.recallCI95)],
      ["False-positive rate", String(r.falsePositiveRate), JSON.stringify(r.falsePositiveRateCI95)],
    ]);
    table(["Category", "Label", "Brilliant / n", "Grades"], Object.entries(r.byCategory).map(([category, v]) => [category, v.label, `${v.brilliant}/${v.n}`, Object.entries(v.grades).map(([g, n]) => `${g} ${n}`).join(", ")]));
    if (Object.keys(r.positiveRejections).length) {
      out("Why positives were not Brilliant:");
      out();
      table(["Decision", "Count"], Object.entries(r.positiveRejections).sort((x, y) => y[1] - x[1]).map(([k, v]) => [k, String(v)]));
    }
    if (r.falsePositiveCases.length) {
      out("False positives:");
      out();
      table(["Case", "Move", "Source"], r.falsePositiveCases.map((c) => [c.id, c.move, c.source ?? ""]));
    }
    if (r.ambiguousCases?.length) {
      out("Ambiguous / borderline cases (not scored; shown for qualitative review):");
      out();
      table(["Case", "Move", "Grade", "Reason"], r.ambiguousCases.map((c) => [c.id, c.move, c.grade, (c.reason ?? "").toString().slice(0, 120)]));
    }
  };
  writeMetrics("Automatically constructed validation corpus", brilliantVal.automaticOnly);
  writeMetrics("Human-audited gold subset", brilliantVal.goldSubset);
}

writeFileSync("docs/validation-report.md", lines.join("\n"));
console.log(`wrote docs/validation-report.md (${lines.length} lines)`);
