// Assemble docs/validation-report.md from the JSON outputs of the corpus tools.
//
//   node scripts/corpus/write-report.mjs
//
// Every number in the report comes from a committed JSON file under data/, so
// the report can be regenerated and checked.
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const read = (path) => (existsSync(path) ? JSON.parse(readFileSync(path, "utf8")) : null);
const GRADES = ["brilliant", "great", "best", "excellent", "good", "book", "inaccuracy", "mistake", "miss", "blunder"];
const LABEL = { brilliant: "Brilliant", great: "Great", best: "Best", excellent: "Excellent", good: "Good", book: "Book", inaccuracy: "Inaccuracy", mistake: "Mistake", miss: "Miss", blunder: "Blunder" };
const lines = [];
const out = (text = "") => lines.push(text);
const table = (header, rows) => {
  out(`| ${header.join(" | ")} |`);
  out(`| ${header.map(() => "---").join(" | ")} |`);
  for (const row of rows) out(`| ${row.join(" | ")} |`);
  out();
};

out("# KnightScope validation report");
out();
out("Generated by `node scripts/corpus/write-report.mjs` from the JSON files under `data/`. Regenerate after any classifier or rating-model change.");
out();

// 1. Golden games before / after.
const goldenBefore = read("data/golden/report-before.json");
const goldenAfter = read("data/golden/report-after.json");
if (goldenBefore && goldenAfter) {
  out("## 1. Great / Brilliant on the two famous games (before → after)");
  out();
  out("Same cached Stockfish searches (Balanced, 150k nodes) for both versions; only the classifier differs.");
  out();
  for (let index = 0; index < goldenAfter.length; index += 1) {
    const before = goldenBefore[index];
    const after = goldenAfter[index];
    out(`### ${after.title}`);
    out();
    const rows = [];
    after.moves.forEach((move, ply) => {
      const old = before.moves[ply];
      if (!["great", "brilliant"].includes(old.grade) && !["great", "brilliant"].includes(move.grade)) return;
      const why = move.grade === "brilliant"
        ? "Brilliant kept"
        : move.grade === "great"
          ? `${old.grade === "brilliant" ? `not Brilliant (${move.brilliant?.decision.replace("rejected: ", "")}); ` : ""}${move.great?.greatReason ?? ""}`
          : old.grade === "brilliant" && move.brilliant
            ? move.brilliant.decision
            : move.great?.decision ?? "";
      rows.push([move.move, LABEL[old.grade], LABEL[move.grade], why.replace(/\|/g, "/")]);
    });
    table(["Move", "Before (ks-review-2.0)", "After", "Why"], rows);
  }
}

// 2. Brilliant adversarial suite.
const suite = read("data/brilliant-suite/report.json");
if (suite) {
  out("## 2. Brilliant adversarial suite");
  out();
  const byCategory = {};
  for (const result of suite.results) (byCategory[result.category] ??= []).push(result);
  const rows = Object.entries(byCategory).map(([category, results]) => [
    category,
    results[0].mustNotBeBrilliant ? "must not be Brilliant" : "sound sacrifice (Brilliant allowed)",
    String(results.length),
    String(results.filter((result) => result.grade === "brilliant").length),
    results.map((result) => `${result.move} → ${LABEL[result.grade]}${result.brilliantDiagnostics ? ` (${result.brilliantDiagnostics.decision})` : ""}`).join("; "),
  ]);
  table(["Category", "Expectation", "Cases", "Brilliant", "Results"], rows);
  const falsePositives = suite.results.filter((result) => result.mustNotBeBrilliant && result.grade === "brilliant").length;
  out(`False positives: **${falsePositives}** of ${suite.results.filter((result) => result.mustNotBeBrilliant).length} must-not cases. Engine: ${suite.engine}, preset ${suite.preset}.`);
  out();
}

// 3. Classification distribution.
const writeDistribution = (title, report, before) => {
  if (!report) return;
  out(`### ${title}`);
  out();
  out(`${report.games} games, ${report.overall.moves} moves. Rates per 1000 moves.`);
  out();
  const header = ["Band", "Moves", ...GRADES.map((grade) => LABEL[grade])];
  const rows = [];
  if (before) rows.push(["**all, before**", String(before.overall.moves), ...GRADES.map((grade) => String(before.overall.per1000[grade] ?? 0))]);
  rows.push([before ? "**all, after**" : "**all**", String(report.overall.moves), ...GRADES.map((grade) => String(report.overall.per1000[grade]))]);
  for (const [band, value] of Object.entries(report.byBand)) rows.push([band, String(value.moves), ...GRADES.map((grade) => String(value.per1000[grade]))]);
  table(header, rows);
  out(`Great per side per game: mean ${report.greatPerSideGame.mean}, max ${report.greatPerSideGame.max}${before ? ` (before: mean ${before.greatPerSideGame.mean}, max ${before.greatPerSideGame.max})` : ""}.`);
  out();
  out("Pathology checks:");
  out();
  const p = report.pathologies;
  out(`- sides with more than 3 Great moves in one game: ${p.sidesWithMoreThan3Great.length}${p.sidesWithMoreThan3Great.length ? ` (${p.sidesWithMoreThan3Great.join(", ")})` : ""}`);
  out(`- Great recaptures: ${p.greatRecaptures.length}; Great although the best alternative still kept a better/winning position with the same engine verdict: ${p.greatWhileDecided.length}`);
  out(`- Brilliant without a detected sacrifice: ${p.brilliantsWithoutSacrifice.length}; Brilliant where a quiet move already won: ${p.brilliantsWhereAlternativeAlreadyWon.length}; Brilliant from a worse position (< 40%): ${p.brilliantsFromLosingPositions.length}; consecutive Brilliants by one side: ${p.consecutiveBrilliantsSameSide.length}`);
  out(`- Miss share of tactical errors (Mistake + Miss + Blunder): ${p.missShareOfTacticalErrors}`);
  out(`- Book: moves losing more than 0.05 EP shown as Book: ${p.bookMovesLosingOver5Points}; last Book ply per game: median ${p.bookPliesMedian}, 95th percentile ${p.bookPliesP95}, max ${p.maxBookPly}; games that show Book again after a non-Book move: ${p.bookAfterNonBookMove} (a theory move graded on its merits because it lost ≥ 0.05, or a transposition back into theory)`);
  out();
  if (report.greatDecisions) {
    out("Great candidates (near-best and unique) and the rule that decided them:");
    out();
    table(["Decision", "Count"], Object.entries(report.greatDecisions).sort((a, b) => b[1] - a[1]).map(([key, value]) => [key, String(value)]));
  }
  if (report.brilliantDecisions) {
    out("Brilliant candidates (near-best moves that give up material):");
    out();
    table(["Decision", "Count"], Object.entries(report.brilliantDecisions).sort((a, b) => b[1] - a[1]).map(([key, value]) => [key, String(value)]));
  }
};
const validationAfter = read("data/validation-corpus/stats-after.json");
const validationBefore = read("data/validation-corpus/stats-before.json");
const ratingCorpusStats = read("data/rating-corpus/stats-after.json");
if (validationAfter || ratingCorpusStats) {
  out("## 3. Classification distribution");
  out();
  writeDistribution("Validation corpus (curated, Balanced preset)", validationAfter, validationBefore);
  if (validationAfter) {
    out("By corpus tag (per 1000 moves):");
    out();
    table(["Tag", "Moves", ...GRADES.map((grade) => LABEL[grade])], Object.entries(validationAfter.byTag).map(([tag, value]) => [tag, String(value.moves), ...GRADES.map((grade) => String(value.per1000[grade]))]));
  }
  writeDistribution("Rated-game corpus (Quick preset), by player rating", ratingCorpusStats, null);
}

// 4–7. Rating.
const summary = read("data/rating-corpus/dataset-summary.json");
const filters = read("data/rating-corpus/FILTERS.json");
const bench = read("data/rating-corpus/benchmark.json");
if (summary && bench) {
  out("## 4. Rating dataset");
  out();
  out(`${summary.games} rated Lichess games → ${summary.samples} game-sides from ${summary.players} players (analyzed at the ${summary.preset} preset, ${summary.engine}).`);
  out();
  table(["Time control", ...Object.keys(summary.byTimeControlAndBand.blitz)], ["blitz", "rapid"].map((tc) => [tc, ...Object.values(summary.byTimeControlAndBand[tc]).map(String)]));
  if (filters) {
    out(`Sources: ${Object.entries(summary.bySource).map(([source, count]) => `${source} ${count}`).join(", ")}. Filters (games dropped): ${Object.values(filters.filters).map((filter) => `${filter.description}: ${filter.dropped}`).join("; ")}. Per-player cap ${filters.perPlayerCap} games; stratified by the players' mean rating band, up to ${filters.perStratum} games per (time control, band).`);
    out();
  }
  out("## 5. Split");
  out();
  out(`${summary.splitMethod[0].toUpperCase()}${summary.splitMethod.slice(1)}. Train ${summary.splits.train}, validation ${summary.splits.validation}, test ${summary.splits.test} game-sides; players appearing in more than one split: **${summary.leakingPlayers}**. ${bench.protocol}`);
  out();
  out("## 6. Held-out accuracy");
  out();
  for (const [tc, report] of Object.entries(bench.timeControls)) {
    out(`### ${tc} (test n = ${report.splits.test})`);
    out();
    table(["Model", "MAE", "Median AE", "RMSE", "R²", "Bias"], Object.entries(report.test).map(([name, m]) => [name, String(m.mae), String(m.medianAe), String(m.rmse), String(m.r2), String(m.bias)]));
    const breakdowns = [["rating band", report.maeByBand], ["meaningful decisions", report.maeByDecisions], ["game result", report.maeByResult], ["phase composition", report.maeByPhaseComposition], ["source", report.maeBySource]];
    for (const [label, data] of breakdowns) {
      const models = Object.keys(report.test);
      out(`MAE by ${label}:`);
      out();
      table([label, "n", ...models], Object.entries(data).map(([key, value]) => [key, String(value.n), ...models.map((model) => String(Math.round(value[model])))]));
    }
  }
  const preset = read("data/rating-corpus/preset-check.json");
  if (preset) {
    out("### Analysis preset (Quick-trained model, Balanced in the app)");
    out();
    out(`${preset.pairs} test game-sides re-analyzed at Balanced; same shipped model on both feature sets.`);
    out();
    table(["Time control", "n", "MAE Quick", "MAE Balanced", "Coverage Quick", "Coverage Balanced", "Mean shift (Balanced − Quick)", "Mean absolute shift"],
      Object.entries(preset.byTimeControl).map(([tc, v]) => [tc, String(v.n), String(v.quick.mae), String(v.balanced.mae), String(v.quick.coverage80), String(v.balanced.coverage80), String(v.meanShiftBalancedMinusQuick), String(v.meanAbsShift)]));
  }
  out("## 7. 80% interval calibration (test)");
  out();
  out("Coverage is close to 80% overall and by game length. By *true* rating band it is not: the estimate is a conditional mean, so it is pulled toward the population average, and players at the extremes (under 1200, over 2400) fall outside their range more often while mid-range players are over-covered. That is the honest limit of what one game reveals; the range is calibrated for a player whose rating you do not already know.");
  out();
  for (const [tc, report] of Object.entries(bench.timeControls)) {
    out(`### ${tc}`);
    out();
    table(["Model", "Coverage of the 80% range", "Mean width"], Object.entries(report.intervals).map(([name, value]) => [name, String(value.coverage80), String(value.meanWidth)]));
    if (report.intervals.ridge.model) {
      const m = report.intervals.ridge.model;
      out(`Shipped interval model: s(n) = sqrt(${Math.round(m.a)} + ${Math.round(m.b)}/n), bounds at ${m.qLow}·s and +${m.qHigh}·s (10th/90th percentiles of out-of-fold standardized residuals).`);
      out();
    }
    const ridge = report.intervals.ridge;
    out("Ridge (shipped) by meaningful decisions:");
    out();
    table(["Decisions", "n", "Coverage", "Mean width"], Object.entries(ridge.byDecisions).map(([key, value]) => [key, String(value.n), String(value.coverage), String(value.meanWidth)]));
    out("Ridge (shipped) by rating band:");
    out();
    table(["Band", "n", "Coverage", "Mean width"], Object.entries(ridge.byBand).map(([key, value]) => [key, String(value.n), String(value.coverage), String(value.meanWidth)]));
  }
}

// 8. Engine.
const liteFull = read("data/golden/lite-vs-full.json");
if (liteFull) {
  out("## 8. Lite vs Full engine");
  out();
  out(liteFull.note);
  out();
  table(["", "Lite", "Full"], liteFull.rows);
}

writeFileSync("docs/validation-report.md", lines.join("\n"));
console.log(`wrote docs/validation-report.md (${lines.length} lines)`);
