// Calibrate the single-game performance model on games with known ratings.
//
// 1) Extract review features with the same pipeline the app uses:
//      node scripts/calibrate-rating.mjs extract lichess_db_standard_rated_2026-08.pgn \
//        --out features.jsonl --limit 2000 --nodes 60000 --workers 4
//    (Lichess monthly dumps are CC0: https://database.lichess.org/ – decompress
//    the .zst first. Only games with WhiteElo, BlackElo and TimeControl are used.)
//
// 2) Fit one model per time control and report holdout error / interval coverage:
//      node scripts/calibrate-rating.mjs fit features.jsonl --out rating-params.json [--write-lib]
//
// Ratings are only comparable within one rating pool: parameters fit on Lichess
// blitz are for Lichess blitz ratings, not Chess.com or FIDE.
import { appendFileSync, readFileSync, writeFileSync } from "node:fs";
import { analyzeGame } from "../lib/analysis-pipeline.ts";
import { parsePgn } from "../lib/chess-review.ts";
import { calibrate } from "../lib/rating-calibration.ts";
import { classifyTimeControl, decisionsFromReviews } from "../lib/rating-model.ts";
import { REVIEW_MODEL_VERSION } from "../lib/review-config.ts";
import { createNodeEnginePool } from "./node-engine.mjs";

function argument(name, fallback) {
  const index = process.argv.indexOf(`--${name}`);
  return index >= 0 ? process.argv[index + 1] : fallback;
}

export function splitPgn(text) {
  return text
    .replace(/\r\n/g, "\n")
    .split(/\n\n(?=\[Event )/)
    .map((game) => game.trim())
    .filter(Boolean);
}

async function extract(file) {
  const out = argument("out", "features.jsonl");
  const limit = Number(argument("limit", "500"));
  const nodes = Number(argument("nodes", "60000"));
  const workers = Number(argument("workers", "1"));
  const engines = createNodeEnginePool(workers);
  let used = 0;
  for (const [index, text] of splitPgn(readFileSync(file, "utf8")).entries()) {
    if (used >= limit) break;
    let game;
    try {
      game = parsePgn(text);
    } catch {
      continue;
    }
    const { WhiteElo, BlackElo, TimeControl, Variant, FEN, Site } = game.headers;
    if (!/^\d+$/.test(WhiteElo ?? "") || !/^\d+$/.test(BlackElo ?? "") || Variant || FEN) continue;
    const timeControl = classifyTimeControl(TimeControl);
    if (timeControl === "unknown" || game.moves.length < 20) continue;
    const analysis = await analyzeGame(game, engines, { primaryNodes: nodes, candidateNodes: nodes });
    const gameId = Site || `game-${index}`;
    const lines = [];
    for (const color of ["w", "b"]) {
      const rating = Number(color === "w" ? WhiteElo : BlackElo);
      for (const decision of decisionsFromReviews(analysis.reviews.filter((move) => move.color === color))) {
        lines.push(JSON.stringify({ ...decision, gameId, color, rating, timeControl, engine: analysis.meta.engineVersion, model: REVIEW_MODEL_VERSION }));
      }
    }
    appendFileSync(out, lines.map((line) => `${line}\n`).join(""));
    used += 1;
    console.log(`${used}/${limit} ${gameId} ${timeControl} ${game.moves.length} plies ${analysis.meta.elapsedMs} ms`);
  }
  engines.forEach((engine) => engine.dispose());
}

function fit(file) {
  const records = readFileSync(file, "utf8").trim().split("\n").filter(Boolean).map((line) => JSON.parse(line));
  const results = {};
  for (const timeControl of [...new Set(records.map((record) => record.timeControl))]) {
    const sides = new Set(records.filter((record) => record.timeControl === timeControl).map((record) => `${record.gameId}:${record.color}`));
    if (sides.size < 100) {
      console.log(`${timeControl}: ${sides.size} game-sides – too few to fit (need ≥ 100), skipped`);
      continue;
    }
    const result = calibrate(records, timeControl);
    results[timeControl] = result;
    const h = result.holdout;
    console.log(
      `${timeControl}: ${result.decisions} decisions · holdout MAE ${h.meanAbsoluteError.toFixed(0)} · r ${h.correlation.toFixed(2)} · ` +
        `80% coverage ${(h.coverage80 * 100).toFixed(0)}% · width ${h.meanIntervalWidth.toFixed(0)} · temper ${result.params.temper}`,
    );
  }
  const out = argument("out", "rating-params.json");
  writeFileSync(out, JSON.stringify({ generatedAt: new Date().toISOString(), modelVersion: REVIEW_MODEL_VERSION, results }, null, 2));
  if (process.argv.includes("--write-lib")) {
    const models = Object.fromEntries(Object.entries(results).map(([tc, result]) => [tc, result.params]));
    writeFileSync(
      new URL("../lib/rating-params.ts", import.meta.url),
      `// Generated by scripts/calibrate-rating.mjs from ${file} on ${new Date().toISOString()}.\n` +
        `import type { TimeControlClass } from "./chess-review.ts";\nimport type { EngineErrorModelParams } from "./rating-model.ts";\n\n` +
        `export const CALIBRATED_MODELS: Partial<Record<TimeControlClass, EngineErrorModelParams>> = ${JSON.stringify(models, null, 2)};\n`,
    );
    console.log("updated lib/rating-params.ts");
  }
}

const [command, file] = process.argv.slice(2);
if (command === "extract" && file) await extract(file);
else if (command === "fit" && file) fit(file);
else if (command) {
  console.error("usage: calibrate-rating.mjs extract <games.pgn> [--out f] [--limit n] [--nodes n] [--workers n]\n       calibrate-rating.mjs fit <features.jsonl> [--out f] [--write-lib]");
  process.exit(1);
}
